---
- name: Create CMaNGOS Docker dir
  file:
    path: '{{ CMANGOS_DOCKER_PATH }}'
    state: directory
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    mode: 0755
  become: true

- name: Create CMaNGOS subdirs
  file:
    path: '{{ cmangos_dir }}'
    state: directory
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    mode: 0755
  loop_control:
    loop_var: cmangos_dir
  loop:
    - '{{ CMANGOS_CONFIG_PATH }}'
    - '{{ CMANGOS_DOCKER_ASSETS_PATH }}'
    - '{{ CMANGOS_DOCKER_STORAGE_PATH }}'
    - '{{ CMANGOS_DOCKER_STORAGE_HONOR_PATH }}'
    - '{{ CMANGOS_DOCKER_LOGS_PATH }}'
    - '{{ CMANGOS_DOCKER_REALMD_LOGS_PATH }}'
    - '{{ CMANGOS_DOCKER_MANGOSD_LOGS_PATH }}'

- name: Apply CMaNGOS Compose template
  template:
    src: docker-compose.yml.j2
    dest: '{{ CMANGOS_DOCKER_PATH }}/docker-compose.yml'
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    mode: '0644'

- name: Apply .env
  template:
    src: env.j2
    dest: '{{ CMANGOS_DOCKER_PATH }}/.env'
    owner: '{{ CMANGOS_HOST_UID }}'
    mode: '0600'

- name: Apply CMaNGOS config templates
  template:
    src: '{{ cmangos_config }}.j2'
    dest: '{{ CMANGOS_CONFIG_PATH }}/{{ cmangos_config }}'
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    mode: '0644'
  loop_control:
    loop_var: cmangos_config
  loop:
    - realmd.conf
    - mangosd.{{ CMANGOS_EXPANSION }}.conf
    - ahbot.conf
    - aiplayerbot.{{ CMANGOS_EXPANSION }}.conf

- name: Deploy WoW client-data
  synchronize:
    src: '{{ CMANGOS_ASSETS_SRC }}/'
    dest: '{{ CMANGOS_DOCKER_ASSETS_PATH }}'
    delete: true
    archive: true
    rsync_opts:
      - --chmod=F0644,D0755

- name: Fix owner and group after assets sync
  file:
    path: '{{ CMANGOS_DOCKER_ASSETS_PATH }}'
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    recurse: true
  become: true
