---
- name: Check Docker existence
  block:
    - name: Check Docker binary existence
      stat:
        path: /usr/bin/docker
      register: docker_installed
    - name: Show error if Docker not isntalled
      fail:
        msg: Docker is not installed
      when: not docker_installed.stat.exists

- name: Configure docker.service stop timeout
  block:
    - name: Create docker.service.d dir
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Set Docker service stop timeout override
      template:
        src: docker-service-override.conf.j2
        dest: /etc/systemd/system/docker.service.d/override.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload Systemd
        - Restart Docker
      become: true

- name: Install rsync
  block:
    - name: Install Rsync to RHEL-based system
      dnf:
        name: rsync
        state: present
        update_cache: true
        install_weak_deps: false
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install Rsync to Debian-based system
      apt:
        name: rsync
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"
      become: true

- name: Install passlib
  block:
    - name: Install Rsync to RHEL-based system
      dnf:
        name: python3-passlib
        state: present
        update_cache: true
        install_weak_deps: false
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install passlib to Debian-based system
      apt:
        name: python3-passlib
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"
      become: true

  when:
    - CMANGOS_INSTALL_PHPMYADMIN
    - CMANGOS_INSTALL_NGINX

- name: Create CMaNGOS Docker dir
  file:
    path: '{{ CMANGOS_DOCKER_PATH }}'
    state: directory
    owner: '{{ CMANGOS_HOST_UID }}'
    group: '{{ CMANGOS_HOST_GID }}'
    mode: '0755'
  become: true
